server:
  port: 0

spring:
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
  application:
    name: eshop-notification
  devtools:
    remote:
      restart:
        enabled: true
  mail:
    host: smtp.gmail.com
    port: 587
    username: nemet.memiyev1@gmail.com
    password:
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000
  mail-from: nemet.memiyev1@gmail.com
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

